Repository Flint-org/Flint-API-Server, pull requests merged in 2023-08, with the labels that each got.

#10 feat: 유저와의 연관관계 부분을 배제한 커뮤니티 관련 모든 엔티티 정의
  .gitignore
  HELP.md
  src/main/java/com/flint/flint/FlintApplication.java
  src/main/java/com/flint/flint/common/BaseTimeEntity.java
  src/main/java/com/flint/flint/community/domain/BoardCategory.java
  src/main/java/com/flint/flint/community/domain/Post.java
  src/main/java/com/flint/flint/community/domain/PostComment.java
  src/main/java/com/flint/flint/community/domain/PostCommentLike.java
  src/main/java/com/flint/flint/community/domain/PostImage.java
  src/main/java/com/flint/flint/community/domain/PostLike.java
  src/main/java/com/flint/flint/community/domain/PostScrap.java
  src/main/java/com/flint/flint/community/specification/BoardCategoryType.java
Labels: Feat

#12 Feat: 유저와 연관 관계를 제외한 모임 도메인 생성
  src/main/java/com/flint/flint/club/controller/comment/ClubCommentController.java
  src/main/java/com/flint/flint/club/controller/main/ClubController.java
  src/main/java/com/flint/flint/club/domain/comment/ClubComment.java
  src/main/java/com/flint/flint/club/domain/comment/ClubCommentLike.java
  src/main/java/com/flint/flint/club/domain/main/Club.java
  src/main/java/com/flint/flint/club/domain/main/ClubCategory.java
  src/main/java/com/flint/flint/club/domain/main/ClubEnvironment.java
  src/main/java/com/flint/flint/club/domain/main/ClubImage.java
  src/main/java/com/flint/flint/club/domain/main/ClubLike.java
  src/main/java/com/flint/flint/club/domain/main/ClubRequirement.java
  src/main/java/com/flint/flint/club/domain/specification/ClubFrequency.java
  src/main/java/com/flint/flint/club/domain/specification/ClubGenderRequirement.java
  src/main/java/com/flint/flint/club/domain/specification/ClubJoinRequirement.java
  src/main/java/com/flint/flint/club/domain/specification/ClubMeetingType.java
  src/main/java/com/flint/flint/club/repository/comment/ClubCommentRepository.java
  src/main/java/com/flint/flint/club/repository/main/ClubRepository.java
  src/main/java/com/flint/flint/club/service/ClubServices.java
  src/main/java/com/flint/flint/club/service/comment/ClubCommentServiceImpl.java
  src/main/java/com/flint/flint/club/service/main/ClubServiceImpl.java
Labels: Feat

#15 feat: 유저와 관련된 엔티티 작성
  gradlew.bat
  src/main/java/com/flint/flint/member/domain/Member.java
  src/main/java/com/flint/flint/member/domain/Notice.java
  src/main/java/com/flint/flint/member/domain/UniversityCertify.java
  src/main/java/com/flint/flint/member/domain/block/ClubBlock.java
  src/main/java/com/flint/flint/member/domain/block/PostBlock.java
  src/main/java/com/flint/flint/member/domain/idcard/IdCard.java
  src/main/java/com/flint/flint/member/domain/idcard/IdCardBox.java
  src/main/java/com/flint/flint/member/domain/report/PostCommentReport.java
  src/main/java/com/flint/flint/member/domain/report/PostReport.java
  src/main/java/com/flint/flint/member/domain/scrap/ScrapClub.java
  src/main/java/com/flint/flint/member/domain/spec/Authority.java
  src/main/java/com/flint/flint/member/domain/spec/Gender.java
  src/main/java/com/flint/flint/member/domain/spec/NoticeType.java
  src/main/java/com/flint/flint/member/domain/spec/OAuthprovider.java
Labels: Feat

#19 feat: 글로벌 예외 처리 핸들러와 응답 공통 폼, 상태 코드 정의
  build.gradle
  src/main/java/com/flint/flint/common/BaseTimeEntity.java
  src/main/java/com/flint/flint/common/ResponseForm.java
  src/main/java/com/flint/flint/common/StatusResponse.java
  src/main/java/com/flint/flint/common/exception/FlintCustomException.java
  src/main/java/com/flint/flint/common/handler/GlobalExceptionHandler.java
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/domain/BoardCategory.java
  src/main/java/com/flint/flint/community/domain/Post.java
  src/main/java/com/flint/flint/community/domain/PostComment.java
  src/main/java/com/flint/flint/community/domain/PostCommentLike.java
  src/main/java/com/flint/flint/community/domain/PostImage.java
  src/main/java/com/flint/flint/community/domain/PostLike.java
  src/main/java/com/flint/flint/community/domain/PostScrap.java
  src/main/java/com/flint/flint/community/spec/BoardCategoryType.java
  src/main/java/com/flint/flint/community/specification/BoardCategoryType.java
  src/main/resources/logback-spring.xml
Labels: Docs, Feat, Chore

#21 feat: 모임 생성, 전체 조회, 단건 조회 API, 예외처리, Test Code
  Dockerfile
  Jenkinsfile.groovy
  build.gradle
  src/main/java/com/flint/flint/club/controller/main/ClubController.java
  src/main/java/com/flint/flint/club/domain/comment/ClubComment.java
  src/main/java/com/flint/flint/club/domain/comment/ClubCommentLike.java
  src/main/java/com/flint/flint/club/domain/main/Club.java
  src/main/java/com/flint/flint/club/domain/main/ClubCategory.java
  src/main/java/com/flint/flint/club/domain/main/ClubEnvironment.java
  src/main/java/com/flint/flint/club/domain/main/ClubImage.java
  src/main/java/com/flint/flint/club/domain/main/ClubLike.java
  src/main/java/com/flint/flint/club/domain/main/ClubRequirement.java
  src/main/java/com/flint/flint/club/domain/main/MemberInClub.java
  src/main/java/com/flint/flint/club/domain/spec/ClubCategoryType.java
  src/main/java/com/flint/flint/club/domain/spec/ClubFrequency.java
  src/main/java/com/flint/flint/club/domain/spec/ClubGenderRequirement.java
  src/main/java/com/flint/flint/club/domain/spec/ClubJoinRequirement.java
  src/main/java/com/flint/flint/club/domain/spec/ClubMeetingType.java
  src/main/java/com/flint/flint/club/domain/spec/MemberJoinStatus.java
  src/main/java/com/flint/flint/club/repository/main/ClubCategoryRepository.java
  src/main/java/com/flint/flint/club/repository/main/ClubCustomRepository.java
  src/main/java/com/flint/flint/club/repository/main/ClubCustomRepositoryImpl.java
  src/main/java/com/flint/flint/club/repository/main/ClubEnvironmentRepository.java
  src/main/java/com/flint/flint/club/repository/main/ClubRepository.java
  src/main/java/com/flint/flint/club/repository/main/ClubRequirementRepository.java
  src/main/java/com/flint/flint/club/repository/main/MemberInClubRepository.java
  src/main/java/com/flint/flint/club/request/ClubCreateRequest.java
  src/main/java/com/flint/flint/club/request/PageImplCustom.java
  src/main/java/com/flint/flint/club/request/PageRequest.java
  src/main/java/com/flint/flint/club/response/ClubDetailGetResponse.java
  src/main/java/com/flint/flint/club/response/ClubsGetResponse.java
  src/main/java/com/flint/flint/club/service/ClubServices.java
  src/main/java/com/flint/flint/club/service/comment/ClubCommentServiceImpl.java
  src/main/java/com/flint/flint/club/service/main/ClubServiceImpl.java
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/domain/PostLike.java
  src/main/java/com/flint/flint/member/domain/report/PostCommentReport.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/com/flint/flint/FlintApplicationTests.java
  src/test/java/com/flint/flint/club/controller/ClubControllerTest.java
  src/test/java/com/flint/flint/club/service/ClubServiceTest.java
Labels: Feat, Test

#29 chore: 개발용 서버 구축
  build.gradle
  src/main/java/com/flint/flint/club/domain/comment/ClubComment.java
  src/main/java/com/flint/flint/club/domain/comment/ClubCommentLike.java
  src/main/java/com/flint/flint/club/domain/main/Club.java
  src/main/java/com/flint/flint/club/domain/main/ClubLike.java
  src/main/java/com/flint/flint/club/domain/main/MemberInClub.java
  src/main/java/com/flint/flint/config/AwsS3Config.java
  src/main/resources/application-dev.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-local.yaml
  src/main/resources/application-local.yml
  src/main/resources/application.yaml
  src/main/resources/application.yml
Labels: Chore, Infra
