Repository Flint-org/Flint-API-Server, pull requests merged in 2023-11, with the labels that each got.

#89 Feat: 게시글 좋아요 API 구현
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/controller/PostCommentUpdateController.java
  src/main/java/com/flint/flint/community/dto/response/PostCommentLikeResponse.java
  src/main/java/com/flint/flint/community/dto/response/PostLikeResponse.java
  src/main/java/com/flint/flint/community/repository/PostCommentLikeRepository.java
  src/main/java/com/flint/flint/community/repository/PostCommentRepository.java
  src/main/java/com/flint/flint/community/repository/PostLikeRepository.java
  src/main/java/com/flint/flint/community/service/PostCommentLikeUpdateService.java
  src/main/java/com/flint/flint/community/service/PostLikeUpdateService.java
  src/test/java/com/flint/flint/community/controller/PostApiControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostCommentUpdateControllerTest.java
Labels: Feat, Test, Refactor

#91 Feat: 전체 게시판에서 게시물 검색
  src/main/java/com/flint/flint/community/controller/PostGetController.java
  src/main/java/com/flint/flint/community/dto/response/AllPostGetResponse.java
  src/main/java/com/flint/flint/community/repository/PostRepository.java
  src/main/java/com/flint/flint/community/service/PostGetService.java
  src/test/java/com/flint/flint/community/controller/PostGetControllerTest.java
Labels: Feat, Test

#93 Refactor: 로그인 리스폰스에 엑세스,리프레쉬 토큰 유효기간 추가
  src/main/java/com/flint/flint/security/auth/AuthenticationService.java
  src/main/java/com/flint/flint/security/auth/dto/AuthenticationResponse.java
Labels: Refactor

#95 Feat: 특정 게시판 검색 API 구현
  src/main/java/com/flint/flint/community/controller/PostGetController.java
  src/main/java/com/flint/flint/community/domain/post/Post.java
  src/main/java/com/flint/flint/community/dto/response/AllPostGetResponse.java
  src/main/java/com/flint/flint/community/repository/BoardRepository.java
  src/main/java/com/flint/flint/community/repository/PostRepository.java
  src/main/java/com/flint/flint/community/service/PostGetService.java
  src/main/java/com/flint/flint/member/domain/main/Member.java
  src/main/java/com/flint/flint/security/auth/AuthenticationController.java
  src/main/java/com/flint/flint/security/auth/AuthenticationService.java
  src/main/java/com/flint/flint/security/auth/dto/RegisterRequest.java
  src/main/java/com/flint/flint/security/oauth/dto/AuthorizionRequestHeader.java
  src/main/java/com/flint/flint/security/oauth/dto/KakaoOAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/dto/NaverOAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/dto/OAuth2UserAttribute.java
  src/test/java/com/flint/flint/community/controller/PostGetControllerTest.java
Labels: Feat, Refactor

#87 feat: 즐겨찾기 게시판 목록 조회 API 구현
  src/main/java/com/flint/flint/community/controller/BoardApiController.java
  src/main/java/com/flint/flint/community/dto/response/BookmarkBoardResponse.java
  src/main/java/com/flint/flint/community/repository/BoardBookmarkRepository.java
  src/main/java/com/flint/flint/community/repository/BoardRepository.java
  src/main/java/com/flint/flint/community/repository/MajorBoardRepository.java
  src/main/java/com/flint/flint/community/service/BoardService.java
  src/test/java/com/flint/flint/community/controller/BoardApiControllerTest.java
  src/test/java/com/flint/flint/community/service/BoardServiceTest.java
Labels: Feat, Test

#97 fix: 유효하지 않은 대분류로 전공 게시판 조회 시 잘못된 결과 반환 오류 수정
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/repository/MajorBoardRepository.java
  src/main/java/com/flint/flint/community/service/BoardService.java
  src/test/java/com/flint/flint/community/service/BoardServiceTest.java
Labels: Fix, Test, Refactor

#99 Refactor: 게시판 내에 게시물 검색 로직
  src/main/java/com/flint/flint/community/controller/PostCommentUpdateController.java
  src/main/java/com/flint/flint/community/controller/PostGetController.java
  src/main/java/com/flint/flint/community/dto/response/PostResponse.java
  src/main/java/com/flint/flint/community/repository/PostRepository.java
  src/main/java/com/flint/flint/community/repository/custom/PostCommentRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/custom/PostRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/impl/PostRepositoryImpl.java
  src/main/java/com/flint/flint/community/service/PostGetService.java
  src/test/java/com/flint/flint/community/controller/PostCommentGetControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostCommentUpdateControllerTest.java
Labels: Refactor

#101 Feat 게시글 스크랩 생성/취소 API
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/controller/PostCommentUpdateController.java
  src/main/java/com/flint/flint/community/repository/PostScrapRepository.java
  src/main/java/com/flint/flint/community/service/PostScrapUpdateService.java
  src/test/java/com/flint/flint/community/controller/PostApiControllerTest.java
Labels: Feat

#103 Feat: 게시글 신고 API
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/domain/post/PostReport.java
  src/main/java/com/flint/flint/community/repository/PostReportRepository.java
  src/main/java/com/flint/flint/community/service/PostReportService.java
  src/main/java/com/flint/flint/mail/controller/MailController.java
  src/main/java/com/flint/flint/mail/service/AuthEmailService.java
  src/main/java/com/flint/flint/mail/service/RandomGenerator.java
  src/main/java/com/flint/flint/mail/service/ReportEmailService.java
  src/main/java/com/flint/flint/mail/service/SendMailService.java
Labels: Feat, Refactor

#108 Refactor: 게시글, 게시글 댓글 좋아요 생성/취소 API 분리
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/controller/PostCommentUpdateController.java
  src/main/java/com/flint/flint/community/service/PostCommentLikeUpdateService.java
  src/main/java/com/flint/flint/community/service/PostLikeUpdateService.java
  src/test/java/com/flint/flint/community/controller/PostApiControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostCommentUpdateControllerTest.java
  src/test/java/com/flint/flint/community/service/PostCommentLikeUpdateServiceTest.java
Labels: Refactor

#110 Fix: 로그인 오류 해결
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/service/PostReportService.java
  src/main/java/com/flint/flint/security/auth/AuthenticationService.java
  src/test/java/com/flint/flint/community/controller/PostApiControllerTest.java
Labels: Fix

#112 Fix: 어트리뷰트 getProviderId 수정
  src/main/java/com/flint/flint/security/oauth/dto/KakaoOAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/dto/NaverOAuth2UserAttribute.java
Labels: Fix

#105 feat: 게시글 목록 조회 API를 페이징을 활용하여 구현
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/community/controller/PostApiController.java
  src/main/java/com/flint/flint/community/domain/post/Post.java
  src/main/java/com/flint/flint/community/domain/post/PostLike.java
  src/main/java/com/flint/flint/community/dto/response/PostListResponse.java
  src/main/java/com/flint/flint/community/repository/PostRepository.java
  src/main/java/com/flint/flint/community/repository/PostRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/PostRepositoryCustomImpl.java
  src/main/java/com/flint/flint/community/service/PostService.java
  src/main/java/com/flint/flint/community/spec/SortStrategy.java
  src/main/resources/application.yml
  src/test/java/com/flint/flint/community/service/PostServiceTest.java
Labels: Feat, Test, Conversation

#114 Refactor: 로그인 /회원가입 예외 로직 추가
  src/main/java/com/flint/flint/common/spec/ResultCode.java
  src/main/java/com/flint/flint/security/auth/AuthenticationService.java
Labels: Refactor

#116 feat: 상세 게시글 조회 API 구현
  src/main/java/com/flint/flint/community/controller/PostGetController.java
  src/main/java/com/flint/flint/community/domain/post/Post.java
  src/main/java/com/flint/flint/community/dto/response/DetailPostResponse.java
  src/main/java/com/flint/flint/community/dto/response/WriterResponse.java
  src/main/java/com/flint/flint/community/repository/PostRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/impl/PostRepositoryImpl.java
  src/main/java/com/flint/flint/community/repository/post/PostRepository.java
  src/main/java/com/flint/flint/community/repository/post/PostRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/flint/flint/community/repository/post_comment/PostCommentRepository.java
  src/main/java/com/flint/flint/community/repository/post_comment/PostCommentRepositoryCustom.java
  src/main/java/com/flint/flint/community/repository/post_comment/PostCommentRepositoryImpl.java
  src/main/java/com/flint/flint/community/service/BoardService.java
  src/main/java/com/flint/flint/community/service/PostCommentGetService.java
  src/main/java/com/flint/flint/community/service/PostCommentLikeUpdateService.java
  src/main/java/com/flint/flint/community/service/PostCommentUpdateService.java
  src/main/java/com/flint/flint/community/service/PostGetService.java
  src/main/java/com/flint/flint/community/service/PostLikeUpdateService.java
  src/main/java/com/flint/flint/community/service/PostReportService.java
  src/main/java/com/flint/flint/community/service/PostScrapUpdateService.java
  src/main/java/com/flint/flint/community/service/PostService.java
  src/test/java/com/flint/flint/community/controller/PostApiControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostCommentGetControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostCommentUpdateControllerTest.java
  src/test/java/com/flint/flint/community/controller/PostGetControllerTest.java
  src/test/java/com/flint/flint/community/service/PostCommentUpdateServiceTest.java
  src/test/java/com/flint/flint/community/service/PostGetServiceTest.java
  src/test/java/com/flint/flint/community/service/PostServiceTest.java
Labels: Feat, Test, Refactor

#120 fix: 토큰 검증에서 (만료 시간 < 현재 시간) 이어야 만료 처리되도록 수정
  src/main/java/com/flint/flint/security/auth/jwt/JwtService.java
Labels: Hotfix

#122 hotfix: 토큰 검증에서 유저의 존재가 없어야 에러가 발생하도록 로직 수정
  src/main/java/com/flint/flint/security/auth/jwt/JwtService.java
Labels: Hotfix

#126 chore: dev 프로필에 슬랙 연동 설정 추가
  src/main/resources/application-dev.yml
Labels: Hotfix, Chore, Infra

#124 Feat: 자체엑세스토큰을 통해 로그인
  src/main/java/com/flint/flint/config/SecurityConfig.java
  src/main/java/com/flint/flint/mail/controller/MailController.java
  src/main/java/com/flint/flint/mail/service/AuthEmailService.java
  src/main/java/com/flint/flint/member/domain/main/Policy.java
  src/main/java/com/flint/flint/security/auth/AuthenticationController.java
  src/main/java/com/flint/flint/security/auth/AuthenticationService.java
  src/main/java/com/flint/flint/security/auth/dto/request/RegisterRequest.java
  src/main/java/com/flint/flint/security/auth/dto/response/AuthenticationResponse.java
  src/main/java/com/flint/flint/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/flint/flint/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/flint/flint/security/jwt/JwtService.java
  src/main/java/com/flint/flint/security/oauth/KakaoOAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/NaverOAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/OAuth2UserAttribute.java
  src/main/java/com/flint/flint/security/oauth/OAuth2UserAttributeFactory.java
  src/main/java/com/flint/flint/security/oauth/dto/AuthorizionRequestHeader.java
Labels: Feat, Fix, Chore
